config/routes.rb
Rails.application.routes.draw do
  root 'marketing#root'

  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }


  namespace :adminka do
    root 'product_lists#index'

    resources :products do # TODO: specify :only [:actions]
      collection do
        get 'is_name_taken'
      end
    end
    resources(:product_lists, except: [:show, :new]) do
      member do
        delete 'product/:product_id' => 'product_lists#remove_product', as: :remove_product_from
        post 'product/:product_id' => 'product_lists#add_product', as: :add_product_to
        get 'products' => 'product_lists#products', as: :products_of
        post 'toggle_done' => 'product_lists#toggle_done', as: :toggle_done
      end

      collection do
        get 'is_name_taken'
      end
    end
  end
end

app/views/layouts/adminka.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoppyVue</title>
    <meta name="apple-mobile-web-app-title" content="Alex Kalinin">
    <meta name='turbolinks-cache-control' content='no-cache' >

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'adminka', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'adminka', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'vue_components', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'vue_components', 'data-turbolinks-track': 'reload' %>

  </head>

  <body data-location="<%= "#{controller_path}##{action_name}" %>">

    <%= render partial: 'adminka/main_menu' %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoppyVue</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>